### PR TITLE
add select native component

### PR DESCRIPTION
**Pull request by zemirco**
Let's take this PR to discuss adding a new select component which behaves pretty much the same way a native select does. Please take a look at the examples. Tests aren't included yet. I will add them when we have decided about the API and whether we want to add this component.

Here is my pro / contra list for the `Nativeselect` vs `Select` component.

**Pro**
- keyboard interactions work out of the box (up/down on focused element, up/down on open list, escape on open list, letter to jump to word starting with this letter, scrolling the underlying page is disabled)
- mobile devices can use their native implementations
- much less code and simpler implementation means less bugs
- on safari and our custom select component you cannot navigate from one element to the next one using using the up and down arrows

some pro arguments are related to the number of bugs we have in the current `Select` component
- current `Select` behaves weird when scrolling
- current `Select` does not have "jump to word when starting letter is pressed"
- current `Select` and `Textfield` are not aligned when next to each other

**Contra**
- impossible to style the `<option>...</option>` content
- impossible to add icons or other content to an `<option />`
- open list looks a bit ugly and the style is different in different browsers

What do you think?

IMO we should use the native select to reduce the area for possible bugs. It also improves the User Experience on mobile devices.

### CODE REVIEW

**Comment by Fa-So** [comment]
Why is the select triangle without meaning?

**Comment by zemirco** [comment]
Good point :+1: Should work now.

**Comment by zemirco** [comment]
any feedback @lipp @Fa-So ?

**Comment by Fa-So** [comment]
What you have done there is very good. You can always find pros and cons if you want. Here is an example of where it works: https://material.angular.io/components/select/overview

We are quite different from material design in our md-components. Not nice, actually.

**Comment by lipp** [comment]
Maybe camelCase? 
`SelectNative` vs `Selectnative`

**Pull request merged**
