### PR TITLE
Slider: Fix implementation

### PR DESCRIPTION
**Pull request by lipp**
also implemented steps. no animation yet.

### CODE REVIEW

**Comment by zemirco** [comment]
One thing I've noticed. 

Clicking on the line left or right from the knob does not move the knob. The current implementation online does it. The knob jumps to where the user has clicked. The default slider also shows this behavior.

**Comment by lipp** [comment]
@zemirco Ok. I will check the click behaviour and try to improve test coverage.

**Comment by zemirco** [comment]
Now we have the `onClick` but what about mobile? Does it work on mobile when clicking the track?

**Comment by lipp** [comment]
Good point! I'll check it out.

**Comment by lipp** [comment]
No. "Touch Click" is not working. Anyhow it felt pretty intuitive to drag the knob instead. I think it is ok this way.

**Comment by lipp** [comment]
@zemirco ready to merge?

**Pull request merged**
