### PR TITLE
Textfield: Add multiline support

### PR DESCRIPTION
**Pull request by lipp**
Adds new component `Textarea`.
Since this component shares most of its implementation with `Textfield`, the code resides in **components/textfield** directory.

Also includes new length (counter) prop implemented by @Fa-So 

Addresses #108.

### CODE REVIEW

**Comment by zemirco** [comment]
How should the textarea work? Should it grow automatically? 

Currently it doesn't and on my machine it looks like the following. As you can see the first line is cropped. I would expect to see both lines at the same time without scrolling.

multiline

**Comment by lipp** [comment]
@zemirco this is clearly not the expected behavior :) I will check this.

**Comment by lipp** [comment]
@zemirco did you rebuild the css?

**Comment by zemirco** [comment]
Yes, rebuilt the CSS. Did you hint `ENTER`? I simply typed `qwd` over and over again without typing `ENTER`.

**Comment by lipp** [comment]
@zemirco ah... you are right. I hit ENTER. The default textarea does not grow in height then...How should the component behave?

**Comment by zemirco** [comment]
True, the default textarea does not grow automatically. So the component looks good.

One last thing :) Shall we rename `TextfieldMultiline` to `Textarea`? Makes it easier to understand for web devs.

**Comment by zemirco** [comment]
and I cannot resize the textarea.

**Pull request merged**
