### PR TITLE
Add textfield suffix prop

### PR DESCRIPTION
**Pull request by lipp**

### CODE REVIEW

**Comment by zemirco** [comment]
I think we should refactor our `Textfield` component now. It has outgrown it's initial purpose. What do you think @Fa-So ?

**Comment by lipp** [comment]
do you want to keep the API and the internal html structure? if not, this will have quite an impact on clipx tests (enzyme and ranorex e2e).

**Comment by lipp** [comment]
tested with Chrome, Firefox, Safari and IE11

**Comment by Fa-So** [comment]
Textfield: I also thought about it. Unfortunately we do not have the right test for the new text component and refactoring is only possible with unit tests. We will certainly make some mistakes that we do not need now. We should rather transform into more important composers. The test department will thank us

**Comment by lipp** [comment]
@Fa-So what do you mean with "more important composers"?

**Pull request merged**
