### PR TITLE
select: decrease space on small devices

### PR DESCRIPTION
**Pull request by zemirco**

### CODE REVIEW

**Comment by lipp** [comment]
can't we handle this via media queries?

**Comment by lipp** [comment]
this approach is of course more flexible, since it is using the "real" space (depending on layout).

**Comment by lipp** [comment]
are you working on #2 too?

**Comment by zemirco** [comment]
yeah that should fix #2 

screenshot from 2017-03-23 11-44-55

media queries won't work. see the attachment. the overflow can also happen on large screens.

**Comment by lipp** [comment]
nice, just checked it.

just one thought: i think the elevation / shadow is barely visible if we go to the "edge". maybe add some margin left and right?

the spec is not clear about this, but have a look at 
https://material.io/guidelines/components/menus.html#menus-simple-menus
and search for "When opened, simple menus attempt to vertically align the "

...

**Comment by lipp** [comment]
closes #2

**Comment by lipp** [comment]
as i think about it i guess the select should be not wider than widest select item...

**Comment by lipp** [comment]
screen shot 2017-03-23 at 12 26 34

**Pull request merged**
